name: 'Stargazers'
description: 'Sync Stargazers'
inputs:
  repotoken:  # id of input
    description: 'repo token or github token'
    required: true
  repo:  # id of input
    description: 'reponame'
    required: true
  owner:  # id of input
    description: 'username'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
